### ISSUE TITLE
Durfen wir eure schöne gh-pages Seite weiterforken?

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/berlin#10]
"weiterforken...." Vielleicht wäre es besser ob ich Englisch shrieb. :smile_cat: 

I'm a programmer & my design skills are schrecklich.  I see that you forked this branch from another (now defunct?) gh-pages.  May I fork your branch & use it for our nascent chapter in Western Massachusetts? Wir sind jeden nur Bauern out here und Amis to boot so I don't think there will be much overlap between our target demographic and yours (i.e. people who look at our site won't look at yours & vice versa, if that matters).

Vielen Dank & let me know if that would be alright! :de: :heart: :us:

**Comment by KenanSulayman** [comment]
Fork ahead..

**Comment by Sequoia** [comment]
thx

**Comment by finnp** [comment]
:heart:
