### ISSUE TITLE
Recurring NodeSchool Meetup

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#11]
Hello everybody :whale: ,

as most of you now we want to turn NodeSchool Berlin into a regular event, where people can come and hack on NodeSchool workshops and help each other out.

It seems like @stryju has some news about this. Do you want to let us now about it? :smile: 

Best,
Finn

**Comment by stryju** [comment]
so, we can have a regular meetup @ Project-A, however some rules apply:
- as for now, the meetup can take place there 1/month
- we get to choose food and drinks, but the budget is set, so no caviar + don p :wink: 
- you need to be nice to each other :grin: 

now, we need to set the preferred date and time

**Comment by finnp** [comment]
Awesome. 
![](http://media.giphy.com/media/7MvDfK7ZmpUe4/giphy.gif)

**Comment by johannhof** [comment]
I've had bad experiences with setting a fixed weekday (every first tuesday of the month). Too many collisions for the same people.

Why not decide one or two months in advance each time?

**Comment by stryju** [comment]
@johannhof we can do that too

we could do it this month too, if we're quick enough and then can agree on the next date

WDYT?

**Comment by finnp** [comment]
I suggest meeting up next Wednesday at 7 pm. 

@stryju Would that work out for you? Otherwise just suggest another day :)

**Comment by damaxsch** [comment]
Oh damn. Am I too late? I would also like to attend these meetings? I am eager to learn more about Node.

**Comment by giantape** [comment]
let us meet up. cannot wait till the next NodeSchol in Berlin.

**Comment by tmundt** [comment]
Did the intended meetup yesterday take place? I would like to join as well.
Am 05.02.2015 13:45 schrieb "giantape" <notifications@github.com>:

**Comment by stryju** [comment]
does the next thursday work for every1?

**Comment by giantape** [comment]
it does for me.

**Comment by finnp** [comment]
There are a few meetups including BerlinCouchDB and Ember.js on Thursday. But I don't think that's much of a problem. Thursday works for me.

**Comment by psturm** [comment]
:+1: for thursday (feb 12th)

**Comment by finnp** [comment]
@nodeschool/berlin Any other votes on the date? Otherwise next meetup will be Thursday, Feb 12th.

**Comment by glaubinix** [comment]
I wont be able to attend as a mentor that day but I am pretty sure there will be enough mentors.

**Comment by finnp** [comment]
@nodeschool/berlin I created a sign-up page for the meetup on Thursday: https://ti.to/nodeschool-berlin/4 :mega: Get your ticket there, so we know how many people to expect.

@stryju Can you check the sign-up page before I send an email to the rest?

**Comment by giantape** [comment]
i did already! nice :) @finn and @stryju thanks!

**Comment by stryju** [comment]
:+1: see you guys on thursday!

**Comment by finnp** [comment]
Awesome. I just sent the :email: out.

**Comment by psturm** [comment]
@finnp Is there a reason this meetup won't show up on http://nodeschool.io/events.html ? Sry, no idea how it works ;)

**Comment by finnp** [comment]
@psturm Nope, i simply forgot to add it there. Now,  it's also visible over there.

**Comment by serapath** [comment]
so there will be a regular thing once a month?
i heard oaklandJS takes place all the time, people just hang and do stuff - no big deal.

I co-organize a meetup at kottbusser tor, called "codingamigos". its a meetup.com/codingamigos
Our main page codingamigos.com was build in sailsJS and we have some javascripters and a lot of ruby folks hanging. The co working space "CO UP" is free for people doing events.
We host codingamigos twice a week (tuesday evening and friday evening), but i guess a regular nodeschool meeting would work there, so it can happen more often than once a month :-)

what do you think? :-)

**Comment by finnp** [comment]
@serapath Cool. I think once a month is an okay timing right now. However everybody can work on the workshoppers from everywhere, so surely people could go to the coding amigo event to continue learning :)

**Comment by giantape** [comment]
agreed! as long as we could continue learning like @finn said, :+1: 
that would be Awesome! :)

**Comment by serapath** [comment]
but codingamigos is not focused on javascript. we have rails developers, php developers, some javascripters and some who do something completely different.

I would love to have a regular javascript meeting with node people who like to follow nodeschool.io style :-) maybe similar to http://oaklandjs.com/

**Comment by finnp** [comment]
@serapath Have you been there yesterday? Forgot to reach out to you, but I also didn't recognize you :) Could you maybe create a new issue concerning codingamigos/co.up? That would be great.

**Comment by finnp** [comment]
Thank you everybody for coming yesterday :tada: :balloon: Here is a photo I tweeted yesterday at the event: https://twitter.com/finnpauls/status/565954188648407040.

I will also send you a follow up email in a few days once we have a few possible dates for the next event. :love_letter:

**Comment by stryju** [comment]
would be cool to ask ppl if they're OK with being on the social media pics, no?

just saying ;-) (privacy is king)

**Comment by finnp** [comment]
@stryju You're right. Going to ask next time :grimacing:

**Comment by stryju** [comment]
just hope no1 minds :)
