### ISSUE TITLE
International Day: May 23rd, 2015

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#12]
There will be an [international day](https://github.com/nodeschool/international-day) on May 23rd. Let's keep that in mind here as a date for a NodeSchool in May. :palm_tree: 

Location: Zenmate

### Schedule
* 11:00 - 11.30 :wave: 
* 11.30 - 13.00 :computer: 
* 13:00 - 14:00 :pizza: 
* 14:00 - 16:00 :computer: 
* 16:00 - 16:30 :coffee: 
* 16:30 - 19:00 :computer: 

### Places for posters
- [x] co.up
- [x] betahaus 
- [x] #unit festival

### Todo
* [x] Find a location
* [x] Create sign up page
* [x] Promote the event (make sure people hear about it, who normally would not)

**Comment by serapath** [comment]
:+1:

**Comment by finnp** [comment]
Hey @danez, at the meetup you told me that researchgate might be able to help out with space. Does that work out? I think space for 50-100 people would be cool. If we start announcing it soon we might be able to get that many signups.

**Comment by danez** [comment]
Hey Finn, 
what is the plan for this day? Is it more like the regular nodeschool meetups (workshop) or talks?
Will it be the whole day (as i just mentioned its a Saturday)?

**Comment by finnp** [comment]
@danez It would be like a regular nodeschool, maybe with a longer introductory talk. Since it's Saturday we could make it whole day, or at least start like past lunch. We're flexible about that.

**Comment by finnp** [comment]
WikiMedia needs their space internally that day.

@judithhartmann @johannhof You both told me that your employers might be able to help out. I don't think space is much of an issue, since I can limit the signup -- but a possibility to have >30 people would be great. Could you ask your employers about it?

@danez Haven't heard from you about RG, yet. If that works out that would be of course great as well :)

Otherwise I still could ask bitcrowd or co.up.

**Comment by johannhof** [comment]
Zenmate would be up for hosting this. We can definitely accommodate more than 30 people if we move some tables. We might also have a budget for drinks and small snacks.

Advantage would be (as I'm responsible) we don't need to rely someone else to open/close the door.

**Comment by finnp** [comment]
@johannhof That is great news. Let's do it at Zenmate then. Budget for drinks and snacks would be great, especially since it's going to be longer than a usual NodeSchool meetup.

**Comment by johannhof** [comment]
I agree. Drinks are not going to be an issue, we'll just need to sort out the food thing (what do we want to order, how much will it cost).

We have separate rooms where one could hold workshops, we should also talk about that.

I think it'd be helpful to do an offline organizational meeting. @finnp If you think that's a good idea can you make a doodle so that other people who are interested in organizing have a chance to join? We can meet at ZenMate.

**Comment by finnp** [comment]
Hey @johannhof, that sounds like a good idea. I suggest that we already meet next week, so that we have enough time left before the event.

@nodeschool/berlin Hey everyone :) If you are interested in helping to plan the international day event, please fill in your availability here: http://doodle.com/mg5maix2cew89gbm

**Comment by Realtin** [comment]
Hab ganz kurzfristig noch ein re:publica Ticket bekommen. Jetzt kann ich Di/Mi/Do gar nicht mehr :/

**Comment by finnp** [comment]
@Realtin Too bad, but that's cool as well :)

@johannhof Somehow I thought we had agreed on a day already. Right now it's only us. But maybe if we agree on a meeting, someone else will join, who knows. Or should we just talk on Monday about it? Let me know what you prefer.

**Comment by finnp** [comment]
We are going to meet Wednesday 4pm at Zenmate, if anyone wants to join us and help organising.

**Comment by johannhof** [comment]
Our in-house designer Martin @velchevski prepared some posters to put up in Berlin.

You can find them here:
https://github.com/nodeschool/berlin/blob/master/poster-international-day-2015.pdf
https://github.com/nodeschool/berlin/blob/master/poster-international-day-2015.sketch

I printed them and will put some up at co-up, betahaus etc. if they let me.

We should start le promoting now

![2015-05-08 13 10 42](https://cloud.githubusercontent.com/assets/2622601/7535471/bef68cf2-f585-11e4-996e-be542463e7e7.jpg)

**Comment by finnp** [comment]
Mentors: Let's meet tomorrow before Berlin.js at about 18.30 at co.up. Let me know here if you think you'l l make it. If not, that's okay too, there's enough time on Saturday to get you started.

**Comment by haikoschol** [comment]
I will probably make it.

**Comment by mfellner** [comment]
Can't make it to co.up tomorrow, sorry. See you all on Saturday!

**Comment by yetzt** [comment]
sorry, can't make it tomorrow.

**Comment by finnp** [comment]
I am going to do an apple pie for Saturday. I still have a lot of eggs, so it's not gonna be vegan.

**Comment by johannhof** [comment]
:cake: :apple: :green_apple:  yay

**Comment by johannhof** [comment]
I'll be able to make it to co-up today.

**Comment by hilja** [comment]
I don't have a pie, but I'll eat one!

**Comment by finnp** [comment]
@hilja Can you bring champagne? :cocktail: :wink:

**Comment by walling** [comment]
Hi all and @finnp, I'm new in the JS/Node.js community in Berlin. I would like to mentor; I've been working with Node.js for several years. I am not quite sure what is expected of me and even if it's too late to sign up as a mentor (I see 3 tickets left)? I might have missed something on the general NodeSchool website.

**Comment by Realtin** [comment]
I'll make a vegan chocolate cake!

**Comment by finnp** [comment]
@walling Cool. Just get a Ticket and come by tomorrow. Here is some info about being a mentor at a nodeschool event http://nodeschool.io/mentor-at-event.html .

**Comment by walling** [comment]
@finnp, cool thanks for the info.

**Comment by johannhof** [comment]
:cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake: :cake:

**Comment by joaoramos** [comment]
I'm sorry guys, I won't make it today. I guess that means more :cake: for you :) Will share videos and stuff? I'd love to stay in the loop.

**Comment by Realtin** [comment]
@joaoramos nooo!! I was soooo looking forward to seeing you again!! :)

**Comment by yetzt** [comment]
`npm eat cake`

**Comment by joaoramos** [comment]
@Realtin me too! maybe next time, with some more vegan chocolate cake :)

**Comment by walling** [comment]
Thanks for today, it was a lot of fun and nice cakes too! :)

**Comment by finnp** [comment]
I've just send the follow up email :love_letter:
