### ISSUE TITLE
missing values...

### ISSUE THREAD

**Issue by Otto404** [nodeschool/berlin#13]
erst mal vielen Dank für Deine Anstrengungen, einen Node-Event aufzuziehen. Das ist sicher viel Arbeit.

### Dennoch fehlt mir das Eine oder Andere. Etwa 
- ein Begrüßungsmail. (Ja, das Event findet statt ...)
- eine Ansicht der offenen / belegten Plätze
- eine Agenda (oh, ich möchte schon wissen, was ich um 22.00 gemacht haben werde)
- eine Liste der Dinge, die sinnvollerweise vorher erledigt werden müssen, damit ich den größtmöglichen Nutzen aus dem Event ziehen kann (etwa: kein Knoblauch, AWS-Account einrichten)
- Notebook mitbringen (ja, nein)
- Bilder, Meinungen etc. vom letzten Mal. (Es gab doch ein letztes Mal, oder?)

etc. etc.

**Comment by serapath** [comment]
:+1:

**Comment by psturm** [comment]
Da die Planung diesmal recht kurzfristig war, springe ich mal ein für @finnp. Ich hoffe ich fasse das korrekt zusammen.

* Event findet statt heute
* Anzahl der Teilnehmer ist mir leider nicht bekannt (aber def. <30)
* Agenda: eher eine Art Workshop. Wir werden zusammen, bzw jeder für sich, die Aufgaben des `learnyounode` tutorials (https://github.com/rvagg/learnyounode) machen, während Mentoren herumlaufen und individuelle Fragen beantworten. Das ganze ist recht frei gestaltet.
Zeitlich ausgelegt auf etwa 2 Stunden, ab 19 Uhr. Soweit ich weiß, wird es auch Snacks und Getränke geben.
* Vorbereitung: Ideal wäre es, wenn nodejs (und git) installiert ist, aber auch da geben wir gern Hilfestellung
* Notebook mitbringen: **ja, definitiv** (wlan steht zur Verfügung)
* Meine persönliche Einschätzung des letzten Treffens: sehr angenehme Runde, wir waren ca 20-25 Leute

Hoffentlich helfen diese Infos.. und wir sehen uns später ;)

**Comment by finnp** [comment]
Danke für dein Feedback, Otto. Ich werde versuchen das beim nächsten Mal mit zu berücksichtigen. Ansonsten hat @psturm ja deine Fragen gut beantwortet :).

**Comment by Otto404** [comment]
> 
> Danke f�r dein Feedback, Otto. Ich werde versuchen das beim n�chsten 
> Mal mit zu ber�cksichtigen. Ansonsten hat 
> @psturm<https://github.com/psturm> ja deine Fragen gut beantwortet :). 



Ja, hat er. Leider (f�r mich) zu sp�t; da ich eine etwas l�ngere Anreise und wenig Zeit habe entschied ich mich (diesmal) nicht zu kommen. Aber ich komme bestimmt. 


LG, Otto

**Comment by finnp** [comment]
Okay, dann sehen wir uns hoffentlich beim nächsten Treffen.

**Comment by giantape** [comment]
:+1:
