### ISSUE TITLE
NodeSchool #5 @Project-A

### ISSUE THREAD

**Issue by psturm** [nodeschool/berlin#14]
## Confirmed date

It's 11.03. at Project-A

----

#### old description

Last time the planning was a bit short termed, so we'd like to start a bit in advance this time.

Current date proposals (CW 11) are:
* 10.03. (tuesday, might collide with upfront meetup)
* 11.03. (wednesday)
* 12.03. (thursday, might collide with coudDB meetup)

Any objections? Please post your vote here.

// edit: fixed the dates, thanks @glaubinix ;)

**Comment by glaubinix** [comment]
Nice. Though I think you mixed up the dates :) they dont correspond with the weekdays next to them.

**Comment by stryju** [comment]
hehe - off by two days :D

**Comment by giantape** [comment]
11.03 (wednesday).

**Comment by maik-** [comment]
10.03. or 11.03. would be ok for me.

**Comment by finnp** [comment]
Okay I guess it is 11.03. then. 
@psturm Can you confirm that the date still works and edit the issue description to only show that date?

**Comment by giantape** [comment]
Awesome!

**Comment by psturm** [comment]
@finnp date is confirmed, on 11th we reserved the room starting from 18:30

**Comment by finnp** [comment]
Okay everyone, I just created a sign up page for the event: https://ti.to/nodeschool-berlin/5 

Sign up there and share it with your friends - especially those who otherwise might not hear about such an event.

**Comment by finnp** [comment]
Thanks for coming everyone :)

If you have any feedback, feel free to post it here. We are going to post possible next dates in a couple of days.

Here's a photo of yesterday (I asked this time :grin: )
![test](https://cloud.githubusercontent.com/assets/841788/6617716/e1ec1a2a-c8bb-11e4-82d5-0c813a6d59e5.jpg)

**Comment by stryju** [comment]
:clap:
