### ISSUE TITLE
German translation for LearnYouNode

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#15]
Hey @nodeschool/berlin and @nodeschool/hamburg,

currently people are working on translating the workshop programs. The learnyounode workshop is already available in japanese, portugese, russian and spanish.

There are two repos/modules that need German translations:
- [x] https://github.com/rvagg/workshopper
- [ ] https://github.com/rvagg/learnyounode

Translating the learnyounode workshop is certainly the bigger effort. So comment here if you're working on it, so we can maybe split up the work.

If you're not familiar with the GitHub workflow (git, forking..), then this is also a good opportunity to learn it (I am happy to help out).

Who wants to help with translating?

Best,
Finn :heart: 

PS: If your mother tongue is not German, translating it into your language would be cool too :)

**Comment by judithhartmann** [comment]
I can help

**Comment by finnp** [comment]
@judithhartmann Awesome. Do you want to start with forking https://github.com/rvagg/workshopper and translate: https://github.com/rvagg/workshopper/blob/master/i18n/en.json ?

**Comment by judithhartmann** [comment]
ok
