### ISSUE TITLE
empty gitter channel

### ISSUE THREAD

**Issue by serapath** [nodeschool/berlin#16]
i'm online every day and `gitter.im` is one of the tabs that always stays open, because it's my IRC replacement. _(you can even use it with a regular irc client)_

I'd would be very neat to hang with some node people from berlin and bounce back and forth the tech everyone is using, just to get in touch more with each other.

wouldn't it be great if all "noders" and "javascripters" from berlin, interested in stuff like nodeschool would have a cosy place to hang online? I see some people already used `http://gitter.im/nodeschool/berlin` to chat, but it's been some months. Could we try again please?

Professionally, as a freelancer, i really feel quite lonely and have to engage in chatting with noders overseas, because i don't know how to connect with my fellow professional folks from berlin.

* I very much would like to learn about what kind of javascript and node trends do you follow?
* which open source projects do you love a lot?
* how does your personal stack look like?

**Comment by finnp** [comment]
Hey,

I will certainly keep an eye on the gitter channel. Other cool channels are:

- https://gitter.im/node-forward/mentors
- https://gitter.im/iojs/io.js
- https://gitter.im/joyent/node

If you have you can also use #node.js on freenode.

**Comment by serapath** [comment]
Mir ging es eher um die community in Berlin :-)
Trefft Ihr euch regelmäßig? Nodeschool ist zwar ganz nett, war aber wenig privat.
Gibt es open source Projekte an denen diejenigen die auf dem nodeschool treffen da waren arbeiten?
Ich würde mich gerne über Trends, Libraries, Frameworks und allem möglichen mit anderen Javascript Programmierern austauschen die in Berlin wohnen.

Online tue ich das bereits, aber mit niemandem aus meinem näheren Umfeld.

**Comment by finnp** [comment]
Hey, in Berlin gibt es noch das Node.js und Berlin.js meetup. Die sind aber wohl noch weniger privat, aber da kannst du dich auf jeden Fall austauschen. NodeSchool ist auf jeden Fall eine kleinere Runde, d.h. da kannst du dich auch mit deinen Tischnachbarn unterhalten. Ansonsten wüsste ich da selbst gerade nichts.
