### ISSUE TITLE
NodeSchool #6 20th April @Project-A 

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#17]
Hey everyone,

NodeSchool #6 will be Monday, April 20th

Colliding dates:
* 08.04 front end learners meetup
* 14.04. up.front meetup
* 15.04. is a Node.js meetup
* 16.04. is a Berlin.js

### To Do

- [x] Agree on a date (check for [collisions](https://hacken.in/berlin))
- [x] Create ti.to page (copy pasta)
- [x] Post event on [nodeschool.io](https://docs.google.com/forms/d/1vYW-Yw82kt_q7WDgBY6gQqFrg3zuD2rDPXEG-cbq7e4/viewform)
- [x] Inform on GiHub
- [x] Inform about event through mailchimp
- [x] Update homepage
- [x] Send reminder to participants at the day of event

Best,
Finn

**Comment by stryju** [comment]
I'm on vacation until 30.03, so can reply after that date.
can we wait until then?

**Comment by finnp** [comment]
@stryju Yes, no problem, as long as we announce it at least a week before. Enjoy your holidays :)

**Comment by finnp** [comment]
@stryju I hope you had a great vacation :) Would be cool if we could announce something soon. Do you now which of the suggested dates fits you?

**Comment by giantape** [comment]
already decided when it comes? which date?

**Comment by finnp** [comment]
@giantape Nope, not yet. Do you have a preference?

**Comment by stryju** [comment]
sorry for the delay - hectic week.

let me get back to you early next week (bud judging by the delay, the week after that is most likely to get more attendants, no?)

**Comment by giantape** [comment]
@finnp for me all that day a fine. tell me if i can do to help. anything!

**Comment by finnp** [comment]
@stryju Yeah no problem. Let's see if Monday 13th would work. Otherwise maybe Friday 17th, but I don't really want to collide with Berlin.js / Node.js meetup.

**Comment by finnp** [comment]
@psturm @stryju Hey it's getting a bit late for the suggested dates. How about 17th (Fr) or 20th (Mo) instead?

**Comment by stryju** [comment]
yeah.

Was supposed to write yesterday.

Monday, 20th works for everyone?

**Comment by finnp** [comment]
Good, works for me. Going to create a sign up page later.

**Comment by finnp** [comment]
@nodeschool/berlin Hey everyone. We will have a NodeSchool on the Monday, 20th April. You can sign up over here: https://ti.to/nodeschool-berlin/6 :sunny:

**Comment by stryju** [comment]
ok, everything confirmed on my side.

also, as a bonus, we'll have tessel.io with all the modules to play around with :-) (courtesy of **project-A**)

**Comment by finnp** [comment]
@stryju That's awesome! You should also get a tessel 2 :wink:

**Comment by stryju** [comment]
we've had tessel v1 for some time already - no real need for v2 :-)

**Comment by finnp** [comment]
Thank you everyone for attending last night :star2: :sparkles:  Going to send a follow-up mail soon.
