### ISSUE TITLE
NodeSchool @#CCC15 (Aug)

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#18]
There are some ideas about a NodeSchool tent at #CCC15. Since it's going to be near Berlin, I thought I am going to cross-link this here: https://github.com/nodeschool/discussions/issues/353

Dates: 13th - 17th August 2015

If someone feels like helping out here, just let me know - or go ahead with it.

**Comment by Realtin** [comment]
I will be there. So I can help out.

**Comment by finnp** [comment]
@Realtin Yay! Forgot to talk to you about this yesterday. I already talked to Florian and we might do a Ruby+JavaScript village. I feel like one of the next steps would be to just create a village page to make it official: https://events.ccc.de/camp/2015/wiki/Static:Villages.

Are yuo using IRC? If so, you should join #rubytown on freenode.

**Comment by lislis** [comment]
I'm probably there as well and would like to help out if possible :D

**Comment by finnp** [comment]
@lislis That's awesome!

I just noticed that there's already a repo for planning Rubytown over here: https://github.com/rubytown/Chaos-Communication-Camp-2015/issues/2 I am going to post something there.

**Comment by ralphtheninja** [comment]
I'll be there as well

**Comment by finnp** [comment]
https://events.ccc.de/camp/2015/wiki/Session:NodeSchool:_Learn_JavaScript!

**Comment by finnp** [comment]
[Event page](https://events.ccc.de/camp/2015/wiki/Session:NodeSchool:_Learn_JavaScript!)
