### ISSUE TITLE
Looking for a Rails Girls Summer of Code Pair!

### ISSUE THREAD

**Issue by Realtin** [nodeschool/berlin#19]
Hey,

I want to apply for the [Rails Girls Summer of Code Program](http://railsgirlssummerofcode.org), working on the [Hoodie Project](https://github.com/hoodiehq) (which is written in JavaScript). My current pair is job hunting right now and she will probably find one pretty soon. She would rather take the job than the Summer of Code Project (if we would get accepted). 
So she urged me to find a new partner. 

I already have two amazing coaches (@finnp & @bastianalbers), a project plan and enthusiasm!
You need to be able to work full-time during 1. Juli - 31. September and some JavaScript knowledge.

If you are interested then contact me: juliakbln@gmail.com
The deadline is on 14. April (this Tuesday!!!)

**Comment by finnp** [comment]
@nodeschool/berlin @judithhartmann ping o/

**Comment by judithhartmann** [comment]
sorry. I'm starting an internship in Ireland this summer, so I won't be able to work full time. But good luck finding a partner!

**Comment by gr2m** [comment]
Hey Julia, are you still looking? We're happy to reach out tomorrow when we're all back to work :)

**Comment by Realtin** [comment]
@gr2m I just got the final call from my new pair! So yes, I have now found someone :)
@judithhartmann Thank you and have a great time in Ireland!

**Comment by finnp** [comment]
That's great news! :cherry_blossom:

**Comment by gr2m** [comment]
w00p, great news, congrats!
