### ISSUE TITLE
NodeSchool #7 @Project-A 

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#21]
Hey everyone,

Let's start thinking about the next meetup already :)

- Mon, 11th: Sign up https://ti.to/nodeschool-berlin/7

### To Do

- [x] Agree on a date (check for [collisions](https://hacken.in/berlin))
- [x] Create ti.to page (copy pasta)
- [x] Post event on [nodeschool.io](https://docs.google.com/forms/d/1vYW-Yw82kt_q7WDgBY6gQqFrg3zuD2rDPXEG-cbq7e4/viewform)
- [x] Inform on GiHub
- [x] Inform about event through mailchimp
- [x] Update homepage
- [x] Send reminder to participants at the day of event

Best,
Finn

**Comment by felixjung** [comment]
Coolio, I'd come to any of those dates.

**Comment by stryju** [comment]
i'm gone for front trends, so 5th-7th is out - will check about 13th

**Comment by finnp** [comment]
@stryju Monday, 11th would work as well, if that's better for you.

**Comment by bnvk** [comment]
Mon, 11th or Wed, 13th work best for me

**Comment by thomasp9** [comment]
Mondays work best for me as well

**Comment by stryju** [comment]
Monday it is, then

there will be pizza, like last time :-)

see you there!

**Comment by thomasp9** [comment]
7pm Mo 11.05. at Project A?

**Comment by finnp** [comment]
@stryju Cool :)

I just opened up the sign up for the meet up: https://ti.to/nodeschool-berlin/7

**Comment by finnp** [comment]
@nodeschool/berlin Hey everybody, in case you missed it, there's a nodeschool meetup tomorrow: https://ti.to/nodeschool-berlin/7

**Comment by felixjung** [comment]
Looking forward to it! Btw. I'm working on a small node project (to teach myself some stuff). Can I do some Q&A to figure out how someone with more experience would judge my approach/code/etc.?

**Comment by finnp** [comment]
@felixjung Yeah generally sure!

**Comment by finnp** [comment]
Thanks everyone for being there tonight! :smiley:
