### ISSUE TITLE
Mentoring during holidays 

### ISSUE THREAD

**Issue by grabbou** [nodeschool/berlin#23]
Hey guys,
If you have any meetings scheduled or planned for the holidays period and are comfortable with `english` speaking mentor I would be more than happy to visit Berlin for a one or two days to meet with you and help others getting started with Node! Wrocław is like 4 hours by train or by car so not even a problem.

**Comment by finnp** [comment]
@grabbou Sounds great. What's the holiday season for you? English speaking mentors are totally cool with us.

**Comment by grabbou** [comment]
Well, actually I can pop in anytime, but as I am still a part-time student I'd prefer anytime after 30.06 :) Can bring some Wrocław stickers so we can do the exchange!

**Comment by FlorianScheel** [comment]
I hope it's OK to mention another tech teaching project here:

@grabbou <https://github.com/grabbou>, you could maybe also join the
upcoming Berlin batch of hackership.org as a Node coach.

**Comment by grabbou** [comment]
Woo, that's awesome idea... I will investigate later. Shall I apply there using the form provided?

**Comment by finnp** [comment]
@grabbou How about coming to CCCamp: https://github.com/nodeschool/berlin/issues/18 in August? I can also let you know once we have a date for NodeSchool in July.

**Comment by grabbou** [comment]
Yeah, both ideas are great. Not sure if I will be able to coach during Hackership as it seems to be a full-time idea (we are busy setting up software house in Poland), but both NodeSchool in July and CCCAamp sounds awesome. Let me know where should I apply and let's spread the Node!

**Comment by haikoschol** [comment]
@grabbou unlike learners, coaches are not required to be present for the full nine weeks. This one would be the form to apply as a coach: http://www.hackership.org/get-involved/#coach
It still mentions Batch-2, but it probably will reach the organizers just the same. Otherwise you could also email team@hackership.org to get in touch.

**Comment by grabbou** [comment]
Nice one, will get in touch with the team! Thank you for the details!

**Comment by finnp** [comment]
@grabbou Hey, just wanted to let you know that our next meetup ist July 29th. Have you figured something out about visiting Berlin?

**Comment by grabbou** [comment]
Hey Hey, yeah, was going to let you know I am still interested. Just need to figure out if I am gonna be available by 29th. Will let you know soon.

**Comment by finnp** [comment]
The CCCamp is over now. Our next meetups are going to be in September.

**Comment by grabbou** [comment]
What time? I'm speaking at WebExpo 19-21 if I am correct.

**Comment by finnp** [comment]
Check the dates on http://wwwtf.berlin/ :) One is on September 21 though.
