### ISSUE TITLE
NodeSchool: Peer Learning

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#25]
Hey everyone,

I noticed recently that a lot of you are interested in more follow-up learning. Here's an idea how you could do more learning together, without the need of having a full event each time.
## How to do it?
1. Pick a location (e.g. a cafe with wifi), date and time where you want to continue learning
   1. You can skip this part and ask others what works for them in the next step.
2. [Post an issue](https://github.com/nodeschool/berlin/issues/new) on this repository with this information. 
   1. Put `Peer Learning` and the Date/Location in the title. 
   2. Ask people to comment if they want to join
   3. You can mention @nodeschool/berlin to make sure people get notified
3. Mentors and other learners then can comment on the issue, when they want to join you.
4. You meet and learn together :bee: 
## Ideas for Locations
- [Betahaus Cafe](https://www.google.com/maps/place/betahaus/@52.502541,13.412198,17z/data=!3m1!4b1!4m2!3m1!1s0x47a84e2d8d4701a9:0x1687d2a7997ddff1)
- [Café Buchhandlung](https://www.google.com/maps/place/Caf%C3%A9+Buchhandlung/@52.526212,13.393735,15z/data=!4m2!3m1!1s0x0:0x400bf85bf1991427?sa=X&ei=U0doVYfcFMicsAGG5YDgBQ&ved=0CBMQ_BIwAA)
- [c-base](http://www.c-base.org/)
- Your own place

This is just an idea, I am open to feedback and we would need to see how well this works :)

Best,
Finn

**Comment by FlorianScheel** [comment]
Hi Finn,

Great idea! If there are more learners that want to meet and work together on their Node skills on a regular basis, one could also try to establish a Node Co-Learning at OpenTechSchool Berlin, just like for Python, Frontend and R. How do you think about that?

Best regards
Florian

**Comment by finnp** [comment]
@FlorianScheel Yes, that is something else we might try to do in the future. However one problem is that we always need people who handle the keys for co.up (so it can't be done without "main organizers"). Also we would probably have to do it on a fixed day of the week, which might not work out for some people. But if you want to go ahead and talk to OpenTechSchool about this, that would be great :smile:
