### ISSUE TITLE
NodeBots @wwwtf.berlin

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#28]
Let's have a NodeBots in September :+1: 

@gorhgorh would do a NodeBots in September for up to 20 people.

Update: September 23

We only need to think about a location. Some kind of maker space would be cool. However basically any space would be possible.

@gorhgorh What are your preferred dates for this?

**Comment by gorhgorh** [comment]
23 is definitely my best one, since I want to attend rejected as well, and I don't have much time these days. 
as for space, as @finnp mentioned while an hackspace "could" be cool, it may happend anywhere, an in between thing could be C-base ? 
anyway I'll ping my CCC friends to ask if they have some space available

**Comment by Realtin** [comment]
I contacted the fablab.berlin. They have a really nice space.

**Comment by Realtin** [comment]
Fablab would host it.   
They need to know some things. From when till when will be the event? And is it a free event or do we charge something?

**Comment by gorhgorh** [comment]
Great !!! Thanks for making this happend :+1: 
About the detail you ask, from my (mentor) point of view
lenght of the event : 
minimum is 2h, 4 is usually a sweet spot BUT if they have a laser cutter on site, and soldering irons, i usually make a demo prototype from start to finish and it adds one hours. 
so i can be something like from 1pm to 6pm if these conditions are met. 

Pricing : 
I usually make the event free of charge, but if they do want to keep the kit at the end I charge the mats costs. 

i don't know how you manage your event usually so @finnp may also have his idea on these details

**Comment by Realtin** [comment]
The Fablab asks if we could do the Workshop from 12 - 5pm, because they have another workshop at 5:30pm. What dou you think?

btw. they do have a laser cutter but didn't awnser me directly if we could use it. But since they are going with the 5h workshop suggestion it could mean that they are fine with us using it.
They also have 2 soldering irons.

**Comment by Realtin** [comment]
if we do it at 12 we have to have a lunch break  or have food there.

**Comment by gorhgorh** [comment]
12 - 5 seems like a good option to me 5h is enough and we can use the meal
time to chat about what are nodebots and what we will do during the WS

2015-09-02 10:18 GMT+02:00 anderspree <notifications@github.com>:

**Comment by Realtin** [comment]
ok great! that it's official now!

now we need a ti.to Event/Ticket Page  @finnp 
with an Event timeline, location information and notebot infos.

I asked the german Make Magizine for sponsoring but they don't have a budget for sponsering anything but they would tweet and maybe writ something o their page about the workshop ... but no money :(
We could tweet about finding a sponsor with our nodeschool account. if we still want some sponsoring.

**Comment by gorhgorh** [comment]
about that, I need to check at home but i DO have 10 ish kit around so while sponsoring is gladly welcome (covering my travel fare would be cool!), but is optional

about tito I'll leave this part to you, but for the info for the workshop i have an outdated version here http://lesnodebots.eu/pre.html <http://lesnodebots.eu/pre.html>. 

so see you in berlin soon then :)

**Comment by finnp** [comment]
Possible Sponsoring:
- 10 NodeBots: 300 Euro
- Food: 70 Euro
- Travel Expenses: 150 Euro

**Comment by Realtin** [comment]
Event Page: https://ti.to/nodeschool-berlin/nodebots

**Comment by gorhgorh** [comment]
plane tickets taken :) I'm arriving the 22th around 9pm

**Comment by Realtin** [comment]
Hey, the fablab asks if we  bring the materials for the lasercutting. @gorhgorh do you?

**Comment by gorhgorh** [comment]
Hey hey, I don't thing bring big sheet of mdf in a plane is a good idea, i would say i won't but the material I use (3mm thick MDF) is very common.
Can we ask them if they do already have some 3mm MDF to sale ? If not what is the size of their laser cutting beds so we can buy some in the morning ?

**Comment by Realtin** [comment]
I have asked them. I don't think it will be a problem.

**Comment by gorhgorh** [comment]
Cool, while we are on this topic, I could not find on their website what kind of files (svg, pdf, ai) and specific details (width of lines, colors) so I can get the file ready ahead of arriving, can you give me an email or ask for theses details, please ?

**Comment by gorhgorh** [comment]
Never mind found it ;) they even have a speedy400 so I exactly know what is needed, perfect

**Comment by Realtin** [comment]
ok great. so they said that they don't have materials but she told me where to get them.

**Comment by gorhgorh** [comment]
ok lets do that wednesday morning ? i'll buy wood glue at the same time. 
ps : @finnp please mail/dm me your phone number so we can catch up easily. 
see you soon

**Comment by Realtin** [comment]
We should be able to get everything we need at this place: http://www.modulor.de/en/store-berlin/

**Comment by finnp** [comment]
@gorhgorh I can't DM you and I don't have your email address :) But if you [follow me](https://twitter.com/finnpauls) on twitter I can do that. Sadly we were not able to get sponsoring for the event, maybe we'll have luck to find a last minute sponsor though.

**Comment by finnp** [comment]
Thank you @gorhgorh again for doing this! Was a pleasure to have you around.
