### ISSUE TITLE
NodeSchool #3 @Project-A

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#4]
Hey everyone,

I would love to do a follow-up meetup quite soon. Maybe even start something recurring like they are doing in [Oakland](https://github.com/nodeschool/oakland/issues/2) now.

Let's collect ideas here when and where to do this.

Best,
Finn

**Comment by giantape** [comment]
o yes please do it again in Berlin. i was missing the last event. but for the next for sure!
@finnp thanks for the info. hope I'll get more info for the next event will be started in Berlin from you guys.

**Comment by stryju** [comment]
just wanted to touch base - some more infos coming early next week ;-)

**Comment by giantape** [comment]
Super! Thanks Stryju. please let me know!

**Comment by stryju** [comment]
ok, it's not "early", but still - i have some news

@finnp maybe we could create a new issue for recurring event? :-)
