### ISSUE TITLE
NodeSchool #19 April 19th

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#42]
- [x] :calendar: Agree on a date April 19th
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io
- [x] :blue_book: Create facebook event
- [x] :speech_balloon:  Post to slack channel 
- [x] :octocat: Inform on GiHub
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage
- [x] :email: send attendee list to mar
- [x] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

Hey everyone! 

/cc @marhigh  @Realtin @boennemann @johannhof

**Comment by marhigh** [comment]
hi! how about 4/19 or 4/26?

**Comment by finnp** [comment]
Both dates would work for me.

**Comment by Realtin** [comment]
I'm leaning towards the 19th .. but I could probably also make it on the 26th

**Comment by johannhof** [comment]
I'm good with both dates as well :smile_cat:

**Comment by chrifpa** [comment]
If you're meeting on 19th I *might* be able to make it :smile:

**Comment by finnp** [comment]
Let's do it on the 19th then. 

@marhigh Can you confirm the date? :memo:

**Comment by marhigh** [comment]
Hi everyone! Happy sunny Monday :D :D :D 
The lounge is booked for the 19th. Any requests on food?

**Comment by Realtin** [comment]
:pizza:  (:

**Comment by marhigh** [comment]
FB: https://www.facebook.com/events/1055171727854500/

**Comment by marhigh** [comment]
Hi peeps! Can we get the link for signing up for the event today? I'd love to start pushing it on the different channels and via email at PAV.

**Comment by finnp** [comment]
wee https://ti.to/nodeschool-berlin/19

**Comment by johannhof** [comment]
Unfortunately I won't be able to make it, work event :fearful:

**Comment by chrifpa** [comment]
I won't be able to make it after all 😞
