### ISSUE TITLE
NodeBots?

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#43]
Hey :)

At the end of July there will be the [NodeBots](http://nodebots.io/) Day, with different events around the globe. We only did one NodeBots workshop in the past (LaserCat with @gorhgorh 🐱 ), but maybe this is something we could participate in. We could focus on building stuff with Tessel for example.

It would be great to have someone with knowledge in Electronics help out with it. 

@mikehenrty @johannhof What do you think about doing this (e.g. at Mozilla)? Not sure yet about whether it would be too stressful this year.

**Comment by gorhgorh** [comment]
I'm available to on component sourcing / ideas / whatever i can help with

**Comment by Realtin** [comment]
cool! @bastianalbers will be happy! :)

**Comment by yoshuawuyts** [comment]
Happy to assist with the Node side of things! :sparkles: - last Nodebots day I attended I ended up helping heaps of people with general JS stuff, if that's of any worth I'd be happy to help ^_^
