### ISSUE TITLE
NodeSchool #21 July 5th @Project A

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#44]
- [x] :calendar: Agree on a date July 5th
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io
- [ ] :blue_book: Create facebook event
- [x] :speech_balloon:  Post to slack channel 
- [x] :octocat: Inform on GiHub
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage
- [x] :email: send attendee list to mar
- [x] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

Hey everyone! 

Suggestions on when to do next months meetup? 

/cc @marhigh @Realtin @boennemann @johannhof @yoshuawuyts @chanakyabhardwajj

**Comment by marhigh** [comment]
I'm taking a bunch of vacation in June! I would only be available June 22, 23, or 28, 29, 30! If that doesn't work I can also ask if another person can host the meetup this time.

**Comment by chanakyabhardwajj** [comment]
I am good with 21st June (or any other date as well).

**Comment by yoshuawuyts** [comment]
Yeah, late June works for sure!

**Comment by Realtin** [comment]
28 and 30.6  work for me also.

**Comment by finnp** [comment]
Okay so I'd suggest to go with 28th of June!

**Comment by marhigh** [comment]
Lounge is booked! 

✌(-‿-)✌

Are we going back to healthy or staying on the pizza track?

**Comment by yoshuawuyts** [comment]
> going back to healthy

ooh healthy? :sparkles:

**Comment by marhigh** [comment]
could be wraps or sandwiches or pizza.... or open to other options, as long as it's easy to eat and not too messy!

**Comment by Realtin** [comment]
just FYI  I had vegan Pizza the other day from: http://www.hallopizza.de/berlin-wedding/vegan ! those where quite nice. 

But I also liked the wraps!

**Comment by marhigh** [comment]
do we have vegans?

**Comment by Realtin** [comment]
not that I actively know of. But probably appreciated nontheless

**Comment by finnp** [comment]
At the last meetup we had a vegan request and people noted this before. So maybe we just try to have a vegan option this time? So maybe we'll have wraps this time.

**Comment by marhigh** [comment]
Can we add this as a question during the signup? I generally like the idea of going into a vegetarian direction but knowing if we have vegans and how many will simplify the food ordering process.

**Comment by Bolland** [comment]
Pro vegan/veggie option and wraps!
Would first week of July also work for you guys? Would love to join but not in Berlin on the 30th (any other Fusionistas? :) )

**Comment by Realtin** [comment]
@Bolland We actually were als discussing pushing it into July so we just changed the Date to July 5th!

**Comment by Bolland** [comment]
Awesome, thanks!! :)

**Comment by Realtin** [comment]
great.. due to me not updating my calender to the new date I know promised to be at an important meeting that evening /o\  💥💥💥

**Comment by johannhof** [comment]
I should be able to make it this time, though! :zap:

**Comment by finnp** [comment]
@Realtin Too bad! 😞 
@johannhof Awesome! 🐎

**Comment by giang91** [comment]
Hi,

my name is Giang and I am a new intern at Horizn Studios and would like to join the next events to learn coding. So the next event is on July 5th at Project A, right?

**Comment by finnp** [comment]
@giang91 Hey, yes exactly, at 7pm. We're also going to post a sign up page soon. Looking forward to see you at the meetup!

**Comment by gnaig** [comment]
Nice! See you.

**Comment by finnp** [comment]
Go get your ticket: https://ti.to/nodeschool-berlin/21 🚀
