### ISSUE TITLE
NodeSchool #22 (August 18th) @Project A next-event

### ISSUE THREAD

**Issue by marhigh** [nodeschool/berlin#45]
- [x] :calendar: Agree on a date
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io
- [x] :blue_book: Create facebook event
- [x] :speech_balloon:  Post to slack channel 
- [x] :octocat: Inform on GiHub
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage
- [x] :email: send attendee list to mar
- [x] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

Hello folks! 

Let's find a date for August :) 

I propose Wed 17th August (as I will be at PAV that day) but am flexible, except for the 23rd-31st.

**Comment by finnp** [comment]
17th August works for me!

**Comment by marhigh** [comment]
Oh wait :/ wednesdays is OTS frontend colearning. How is the 16th or 18th?

**Comment by finnp** [comment]
18th works for me as well.

**Comment by gnaig** [comment]
18th works for me too

**Comment by marhigh** [comment]
Lounge is booked 👍

**Comment by Realtin** [comment]
https://ti.to/nodeschool-berlin/22

**Comment by marhigh** [comment]
https://www.facebook.com/events/1677991929189791/
