### ISSUE TITLE
NodeSchool #23 in October 🎃 👻 

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#46]
- [x] :calendar: Agree on a date
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io
- [x] :blue_book: Create facebook event
- [x] :speech_balloon:  Post to slack channel 
- [x] :octocat: Inform on GiHub
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage
- [x] :email: send attendee list to mar
- [x] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

Hey, let's find a date for the next NodeSchool 😄

**Comment by yoshuawuyts** [comment]
I'll be in town only from 24-28 of Oct; happy to help if it's in that week

**Comment by finnp** [comment]
Thursday 27th would work for me.

**Comment by Realtin** [comment]
I'm not in town from 24th-29th :D 
but I'm also pretty stressed out from work, They want to release the MVP at the end of the month and everyone is on edge in my department :/   so what I'm saying is, maybe you should do it without me this month.

**Comment by johannhof** [comment]
26 - 28 Oct doesn't really work for me either, but don't let that hold you back if it works for enough people :)

**Comment by marhigh** [comment]
the 27th also works for me

**Comment by marhigh** [comment]
Hey everyone! Should I organize the lounge on the 27th? Do we have enough mentors?

**Comment by finnp** [comment]
Yes let's do the 27th.

**Comment by marhigh** [comment]
Cool! Should we already open the ticket page? It's already quite close by to the date.

**Comment by finnp** [comment]
https://ti.to/nodeschool-berlin/23

**Comment by marhigh** [comment]
FB event :) https://www.facebook.com/events/558104201041878/
