### ISSUE TITLE
NodeSchool #24 October 20th

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#47]
Hey,

we haven't done a NodeSchool in pretty much exactly one year. Let's see if we can get this started again ☺️ 

Below the check-list that we used in the past, but I think we'll might have to re-plan some stuff first.

/cc @Realtin @pup 

- [x] :calendar: Agree on a date  ➡️  **Fri 20.October**
- [x] :memo: Create ti.to page ➡️  https://ti.to/nodeschool-berlin/24
- [x] :school: :bear: Post event on nodeschool.io
- [ ] :blue_book: Create facebook event
- [x] :speech_balloon:  Post to slack channel 
- [x] :octocat: Inform on GiHub
- [ ] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [ ] :house: Update homepage
- [ ] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

**Comment by Realtin** [comment]
The Week after BerlinJS (if there is BerlinJS) is probably good
**Tuesday, October 24**
**Thursday October 26** . (but the potential new location at Mozilla is occupied that day)

**Comment by finnp** [comment]
I'm not going to be in Berlin on October 24. Also not sure about October 26 yet. The other weeks could work for me.

**Comment by pup** [comment]
i'm free for the rest of october!

**Comment by dstankovic** [comment]
Hey there, I'm new in Berlin JS community, but more than willing to help since I've already participated as a mentor before.

**Comment by johannhof** [comment]
In case you want to host it in the Mozilla Community Space (we'd love that), please let me know (or use the form on the website) so that I can get you permanent access to the space and arrange for food sponsoring.

Calendar is here: https://mozilla-berlin.github.io/

Looking forward to it!

**Comment by Realtin** [comment]
What do people think about **Friday 20. October**??

**Comment by finnp** [comment]
Works for me!

**Comment by pup** [comment]
sounds good to me! and thanks in advance, @johannhof!!

**Comment by yoshuawuyts** [comment]
Count me in too!

**Comment by Realtin** [comment]
I submitted the Event to the [Mozilla Community Space Calender](https://mozilla-berlin.github.io/) and create a [ti.to Event](https://ti.to/nodeschool-berlin/24) page (but paused the ticket 'sale' until Mozilla approves the Event)

**Comment by finnp** [comment]
The ti.to event is live by the way: https://ti.to/nodeschool-berlin/24. The tickets are only for learners, you don't have to get one as an organizer/mentor.

**Comment by pup** [comment]
does anyone want to tweet about it?

**Comment by pup** [comment]
here we go: https://twitter.com/nodeschoolbln/status/917313370860216320

**Comment by pup** [comment]
wow, looks like we're sold out of tickets!

**Comment by dstankovic** [comment]
Hello, should I sign somewhere or just jump in tomorrow? Cheerio

**Comment by Realtin** [comment]
Hey @dstankovic we are sold out of learner tickets, but it should be fine if you are also interested to coach/mentor :)

**Comment by dstankovic** [comment]
@Realtin yep, that's what I thought as mentioned above :) See ya then

**Comment by boennemann** [comment]
I'm not 💯% sure yet, but maybe I can make it as a mentor tonight.

**Comment by pup** [comment]
thanks everyone for coming!
