### ISSUE TITLE
NodeSchool #25 on November 10th

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#49]
Hey,

so yeah let's make this a regular thing again ♻️ ☺️ .

Let's look for a date in November. I think it would be nice to use the Mozilla space again.

Also I think it would be cool to make a [choo](https://github.com/choojs/choo)-themed nodeschool next time. /cc @yoshuawuyts 

- [x] :calendar: Agree on a date  November 10th
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io
- [x] :bird: Tweet about the event
- [x] :house: Update homepage
- [ ] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

**Comment by Realtin** [comment]
🚂  

if we want to do friday again, the 24.11 is the last friday of the month and the day after http://berlinjs.org/

**Comment by yoshuawuyts** [comment]
I might be out of town during late November / Early December; yesterday was fun tho, having more events would be great! :tada: :tada: :tada: :tada:

**Comment by pup** [comment]
i can only do the first two november weekends, but basically anytime during the rest of the week!

**Comment by Realtin** [comment]
Friday November 10th ? or is that too short notice?

**Comment by pup** [comment]
works for me!

**Comment by finnp** [comment]
Works for me as well.

**Comment by finnp** [comment]
@Realtin Is it November 17th now? Saw that you updated the website.

**Comment by Realtin** [comment]
Oh I misremembered!  We have to change it .. arg!

**Comment by ProfNandaa** [comment]
We're starting a NS here in Nairobi and I think I like how you folks run your stuff! I'll be following keenly. Any way I can join in remotely for the November meetup?

**Comment by finnp** [comment]
@ProfNandaa Thank you ☺️ Sure. I suppose it would be the easiest if you joined the #nodeschool channel on https://berlinjs-slack.herokuapp.com/.
