### ISSUE TITLE
Interested in the next NodeSchool? Have a look here.

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#5]
Hello!

If you are interested in the next NodeSchool event, you have several options.
- Show your interest or help out with the  [next NodeSchool](https://github.com/nodeschool/berlin/labels/next-event)
- If you don't have a GitHub account, you can susbcribe to the [NodeSchool Reminder](http://eepurl.com/4yuRb) here. We will only send you informations about upcoming events. Nothing more, we promise.
- You can watch this repository for new activity.

Best,
Finn

**Comment by giantape** [comment]
Hey Finn,
it is a lttle bit to late for me but when do you want to plant for the next NodeSchool Event?
iam a new in Node and want to know more about Node. would be great thanks if you can give me some info. 
Thanks, Gesang

**Comment by ninalucia** [comment]
Hi Finn,

Sorry for the late reply, I don't live in Berlin anymore so I cannot help
out.
Could you please delete me from the e-mail?

BEst,
Nina



2015-01-08 21:33 GMT+01:00 giantape <notifications@github.com>:

**Comment by finnp** [comment]
@giantape There is currently no date for the next NodeSchool. I'm currently not in Berlin, but I will be again starting from February. If you feel like it, open a new issue called "NodeSchool #4", maybe with suggestions on a date, so we can start planning the next event.

@ninalucia Too bad! If you don't want to receive emails from GitHub anymore you need to unsubscribe from this repository or deactivate getting mails from GitHub.

**Comment by ninalucia** [comment]
@finnp I will. Keep up the good work!

**Comment by Nienor** [comment]
I would be interested to attend :) I could help planing the event too.

**Comment by tmundt** [comment]
I am also in, what are your plans, guys?

**Comment by psturm** [comment]
Guess, we just have to agree on a date (see https://github.com/nodeschool/berlin/issues/11)

**Comment by finnp** [comment]
@Nienor Great :) Yeah, like @psturm said we just need to agree on the next meetup date.

**Comment by serapath** [comment]
Will there be stickers tomorrow? :-) I made some space on my notebook xD

**Comment by finnp** [comment]
@serapath yes, there will be :star:

**Comment by giantape** [comment]
nice :) .. i like :)

**Comment by finnp** [comment]
@Nienor You haven't been at a meetup yet, right? I could need some help for organising this event: https://github.com/nodeschool/berlin/issues/12. The plan is to have a bit bigger workshoper on that day.

**Comment by marhigh** [comment]
Hey Finn! Shall we set up dates for Oct & Nov Nodeschool @ Project A?
