### ISSUE TITLE
NodeSchool #26 on December 8th

### ISSUE THREAD

**Issue by pup** [nodeschool/berlin#50]
let's plan early! i think sometime during the first two weeks would be best

- [x] :calendar: Agree on a date: __8th Dec__
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io
- [x] :house: Update homepage
- [x] :money_with_wings: Start ticket sale
- [x] :bird: Tweet about the event

**Comment by finnp** [comment]
I looked at the Mozilla calendar, here's a few suggestions: 

- Thursday, 14th December
- Wednesday, 6th December
- Friday, 8th December

I think I prefer 14th December.

**Comment by pup** [comment]
i can make the 14th work, yeah

**Comment by pup** [comment]
date is decided! 14th it is
