### ISSUE TITLE
Biweekly NodeSchool Co-Learning

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#54]
Hey @nodeschool/berlin 

We're planning on trying out doing NodeSchool biweekly as in every 2 weeks. Let's decide on a schedule here and see what else needs to be planned.

TBD
- [x] Mozilla Keycard for at least one more person
- [x] Decide on a schedule
- [x] would mozilla sponsor 🍕  for this?
- [x] Should we use meetup.com?

Suggested schedules:

- **Every second Thursday** (offset to *Open Mozilla Night*)  react with ❤️ 
Pro: People could come every Th to do JavaScript

- **Every second Wednesday** (offset to *Rust Hack and Learn*)  react with  😃
Pro: People could come every We to learn stuff
Con: Wednesdays is the OTS Web Frontend Co-Learning

- **Every second Friday**  react with  🎉
Pro: end of the week (?)
Con: Maybe not that popular for people?

Let me know if you have other day suggestions, or concerns with the ones above. Also feel free to vote with Github reactions ☺️

**Comment by Realtin** [comment]
Wednesday maybe clashes with the Web-frontend Meetup from Open Techschool which targets a similar audiance

**Comment by johannhof** [comment]
>  would mozilla sponsor 🍕 for this?

I have a positive feeling, but we're currently in the process of sorting out community event planning/budgeting for 2018 (I know it's 2018 already :stuck_out_tongue:), so I'll get back to you with a definitive answer later. In the short term we can just continue to do it.

**Comment by bastianalbers** [comment]
You're more than welcome to do that through the OTS meetup account :)

**Comment by Realtin** [comment]
@finnp I put it in the calendar!  next Nodeschool (after tomorrow) will be February 8.

**Comment by finnp** [comment]
Here's the Meetup link for the next nodeschool, it will automatically show up every 2 weeks on meetup i think: https://www.meetup.com/opentechschool-berlin/events/247138181/
