### ISSUE TITLE
Electron Workshop

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#56]
Hey ☺️ 

I met @vanessayuenn at jsconf this year (who works on the @electron  team) and we thought that it would be cool to organize an electron workshop in berlin at some point.

Right now the nodeschool materials are a bit sparse for this, [elementary-electron](https://github.com/maxogden/elementary-electron) is pretty short.

Maybe we can come up with ideas here. I think it would be cool to make it a full-day event at a weekend at some point.

/cc @nodeschool/berlin

**Comment by Realtin** [comment]
yes! That would be wonderful.

Ideas:
- Game of Life
- Password generator (generating passwords that you can remember)
- Pixel Art Drawing app

**Comment by finnp** [comment]
Found a great website [electron-essential](http://jlord.us/essential-electron/) by @jlord. This could be turned in to an introductory presentation.

Also there is https://electronjs.org/docs/tutorial/first-app

**Comment by vanessayuenn** [comment]
👋hello y'all! Thank you @finnp for pushing this forward! I have sources for materials that have been used in the past for electron workshops. But first I would like to know how long are we thinking when we say "a full-day event"?

**Comment by oe** [comment]
@vanessayuenn 10/11am - 4/5pm i'd assume

**Comment by finnp** [comment]
@vanessayuenn If there is a workshop format/length that you prefer to do, we can also make it an evening event or something :)

**Comment by bastianalbers** [comment]
I'd love to support this from the OTS&CSSclasses side and take part / help coaching and so on, so keep me in the loop :)
