### ISSUE TITLE
Logo Proposals

### ISSUE THREAD

**Issue by johannhof** [nodeschool/berlin#9]
Hey,

friends of mine are starting a design collective/agency (or something like that) and I told them we need a cool logo for Nodeschool Berlin, so they came up with two logo ideas:

![Proposal 1](https://cloud.githubusercontent.com/assets/2622601/5825160/97f1aa92-a0e9-11e4-8df3-2e5a500e538d.png)

![Proposal 2](https://cloud.githubusercontent.com/assets/2622601/5825175/a7660068-a0e9-11e4-8947-0734f531ae7f.png)

They're free to use, obviously, but if we actually use one they'd like to show it off on their new website.

Feedback is welcome :)

**Comment by finnp** [comment]
Awesome, finally someone took a stab at this :+1: I like them both, but I think the first one looks more like "NodeSchool". 

Also I would prefer it to be more of a mash-up between the NodeSchool building and the Brandenburger Tor, similar to this one: http://nodeschool.io/hamburg/images/logo.svg

Alternatively maybe turning the Reichstag into a NodeSchool style building.

**Comment by johannhof** [comment]
I agree, mashup would be cool. I'll ask if they want to give that a try. I'm not sure if the Brandenburger Tor will work out with the Nodeschool building though.

I think the second one comes from https://raw.githubusercontent.com/nodeschool/nodeschool.github.io/master/images/nodeschool-hex.png

**Comment by feju** [comment]
Nice job! I never managed to take another look at this.

**Comment by maxogden** [comment]
Just saw this thread. I really like the bear!!!!!

**Comment by finnp** [comment]
@johannhof I am going to order the first sticker soon. :+1:

**Comment by johannhof** [comment]
@finnp Nice, I mentioned Brandenburger Tor idea but didn't pursue it much further, I think they couldn't really make it fit. I like the bear imo :)

**Comment by finnp** [comment]
Hey @velchevski! Maybe you could try and create another version of the sticker? I feel like the bear looks quite good, but I would love it to be more coherent. Here's a NodeSchool sticker that I especially like: http://nodeschool.io/hamburg/images/logo.svg. Also here is a list of other cool stickers http://nodeschool.io/hexdex.

**Comment by velchevski** [comment]
@finnp I'd definitely give it a spin during the weekend! I think I can make it work. Would try with the Brandenburger Tor or Fernsehturm. Thanks for the invite by the way.

**Comment by finnp** [comment]
@velchevski Hey Martin, are you still on this? I would love to print some new stickers soon.

**Comment by marhigh** [comment]
Hey everyone!  I am wrapping up the article I wrote about NodeSchool for Project A's blog. We want to double-check if we can use the NodeSchool logo for it. Is that ok?

**Comment by finnp** [comment]
@marhigh Yeah sure!
